//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Grades_Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Student_Grades_Library")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ScoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First {
            get {
                return this.FirstField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstField, value) != true)) {
                    this.FirstField = value;
                    this.RaisePropertyChanged("First");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last {
            get {
                return this.LastField;
            }
            set {
                if ((object.ReferenceEquals(this.LastField, value) != true)) {
                    this.LastField = value;
                    this.RaisePropertyChanged("Last");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Scores {
            get {
                return this.ScoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoresField, value) != true)) {
                    this.ScoresField = value;
                    this.RaisePropertyChanged("Scores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IStudentGradeService")]
    public interface IStudentGradeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetStudentAvgGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetStudentAvgGradeResponse")]
        float GetStudentAvgGrade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetStudentAvgGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetStudentAvgGradeResponse")]
        System.Threading.Tasks.Task<float> GetStudentAvgGradeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetStudentMinGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetStudentMinGradeResponse")]
        int GetStudentMinGrade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetStudentMinGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetStudentMinGradeResponse")]
        System.Threading.Tasks.Task<int> GetStudentMinGradeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetClassAvgGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetClassAvgGradeResponse")]
        float GetClassAvgGrade();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetClassAvgGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetClassAvgGradeResponse")]
        System.Threading.Tasks.Task<float> GetClassAvgGradeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetFStudentBelowAvgGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetFStudentBelowAvgGradeResponse")]
        Student_Grades_Client.ServiceReference.Student[] GetFStudentBelowAvgGrade();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetFStudentBelowAvgGrade", ReplyAction="http://tempuri.org/IStudentGradeService/GetFStudentBelowAvgGradeResponse")]
        System.Threading.Tasks.Task<Student_Grades_Client.ServiceReference.Student[]> GetFStudentBelowAvgGradeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetStudentList", ReplyAction="http://tempuri.org/IStudentGradeService/GetStudentListResponse")]
        Student_Grades_Client.ServiceReference.Student[] GetStudentList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentGradeService/GetStudentList", ReplyAction="http://tempuri.org/IStudentGradeService/GetStudentListResponse")]
        System.Threading.Tasks.Task<Student_Grades_Client.ServiceReference.Student[]> GetStudentListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentGradeServiceChannel : Student_Grades_Client.ServiceReference.IStudentGradeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentGradeServiceClient : System.ServiceModel.ClientBase<Student_Grades_Client.ServiceReference.IStudentGradeService>, Student_Grades_Client.ServiceReference.IStudentGradeService {
        
        public StudentGradeServiceClient() {
        }
        
        public StudentGradeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentGradeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentGradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentGradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float GetStudentAvgGrade(int id) {
            return base.Channel.GetStudentAvgGrade(id);
        }
        
        public System.Threading.Tasks.Task<float> GetStudentAvgGradeAsync(int id) {
            return base.Channel.GetStudentAvgGradeAsync(id);
        }
        
        public int GetStudentMinGrade(int id) {
            return base.Channel.GetStudentMinGrade(id);
        }
        
        public System.Threading.Tasks.Task<int> GetStudentMinGradeAsync(int id) {
            return base.Channel.GetStudentMinGradeAsync(id);
        }
        
        public float GetClassAvgGrade() {
            return base.Channel.GetClassAvgGrade();
        }
        
        public System.Threading.Tasks.Task<float> GetClassAvgGradeAsync() {
            return base.Channel.GetClassAvgGradeAsync();
        }
        
        public Student_Grades_Client.ServiceReference.Student[] GetFStudentBelowAvgGrade() {
            return base.Channel.GetFStudentBelowAvgGrade();
        }
        
        public System.Threading.Tasks.Task<Student_Grades_Client.ServiceReference.Student[]> GetFStudentBelowAvgGradeAsync() {
            return base.Channel.GetFStudentBelowAvgGradeAsync();
        }
        
        public Student_Grades_Client.ServiceReference.Student[] GetStudentList() {
            return base.Channel.GetStudentList();
        }
        
        public System.Threading.Tasks.Task<Student_Grades_Client.ServiceReference.Student[]> GetStudentListAsync() {
            return base.Channel.GetStudentListAsync();
        }
    }
}
